import { json, noDb, toCols, CREATE_SQL, adminRole, forbidden } from "../_lib.js";

// POST /api/seed -> one-time load of the built-in calendar into an empty database.
// The seed file is generated by build_site.py from events_data.py and shipped with the site.
// Refuses to touch a database that already has rows, so it can never overwrite live edits.
export async function onRequestPost({ request, env }) {
  const err = noDb(env); if (err) return err;
  const role = adminRole(request, env);
  if (!role || role === "desk") return forbidden();
  await env.DB.prepare(CREATE_SQL).run();
  const { c } = await env.DB.prepare("SELECT COUNT(*) AS c FROM events").first();
  if (c > 0) return json({ seeded: false, note: `The database already holds ${c} events. Nothing changed.` });
  const res = await env.ASSETS.fetch(new URL("/events_seed.json", request.url));
  if (!res.ok) return json({ error: "events_seed.json is missing from the build" }, 500);
  const rows = await res.json();
  const stmts = rows.map(r => {
    const { cols, vals } = toCols(r);
    return env.DB.prepare(`INSERT INTO events (${cols.join(",")}) VALUES (${cols.map(() => "?").join(",")})`).bind(...vals);
  });
  await env.DB.batch(stmts);
  return json({ seeded: true, count: rows.length });
}
